/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  agoraPortalUrl?: string;
  contactEmail?: string;
  defaultShareImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  disclaimer?: string;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Lead = {
  _id: string;
  _type: "lead";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  source?: "keep-in-touch" | "site-submission";
  firstName?: string;
  lastName?: string;
  email?: string;
  phone?: string;
  investorType?: string;
  checkSize?: string;
  accreditedConfirmed?: boolean;
  propertyAddress?: string;
  message?: string;
  submittedAt?: string;
  emailed?: boolean;
  exportedToAgora?: boolean;
};

export type Testimonial = {
  _id: string;
  _type: "testimonial";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  quote?: string;
  attribution?: string;
  descriptor?: string;
  investorSince?: number;
  consentOnRecord?: boolean;
  featured?: boolean;
  order?: number;
};

export type FocusCard = {
  _id: string;
  _type: "focusCard";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  description?: string;
  order?: number;
};

export type HeroStat = {
  _id: string;
  _type: "heroStat";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  figure?: string;
  label?: string;
  order?: number;
};

export type TeamMember = {
  _id: string;
  _type: "teamMember";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  role?: string;
  bio?: string;
  photo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  linkedin?: string;
  order?: number;
};

export type PropertyReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "property";
};

export type Post = {
  _id: string;
  _type: "post";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  publishedAt?: string;
  category?:
    | "municipal-partnership"
    | "design"
    | "operations"
    | "market"
    | "announcement";
  excerpt?: string;
  heroImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  body?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
        _key: string;
      }
  >;
  relatedProperty?: PropertyReference;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type Property = {
  _id: string;
  _type: "property";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  assetClass?:
    "multifamily" | "mixed-use" | "townhomes" | "industrial" | "senior";
  status?:
    | "stabilized"
    | "lease-up"
    | "under-construction"
    | "renovation-complete"
    | "sold";
  city?: string;
  state?: string;
  coordinates?: Geopoint;
  metraStation?: string;
  walkMinutes?: number;
  unitCount?: number;
  retailUnitCount?: number;
  squareFeet?: number;
  yearBuilt?: number;
  yearRenovated?: number;
  cardBlurb?: string;
  overview?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  businessPlan?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  gallery?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  }>;
  dealStory?: {
    acquired?: string;
    executed?: string;
    exited?: string;
    equityMultiple?: string;
    exitYear?: number;
  };
  publiclyOffered?: boolean;
  featured?: boolean;
  order?: number;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | SiteSettings
  | SanityImageCrop
  | SanityImageHotspot
  | Lead
  | Testimonial
  | FocusCard
  | HeroStat
  | TeamMember
  | PropertyReference
  | Post
  | Slug
  | Property
  | Geopoint
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset;

// Source: src/sanity/queries.ts
// Variable: ALL_PROPERTIES_QUERY
// Query: *[_type == "property"] | order(order asc) {    _id, title, "slug": slug.current, assetClass, status, city, state,    metraStation, walkMinutes, unitCount, retailUnitCount, yearBuilt, cardBlurb,    "image": gallery[0]  }
export type ALL_PROPERTIES_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  assetClass:
    "industrial" | "mixed-use" | "multifamily" | "senior" | "townhomes" | null;
  status:
    | "lease-up"
    | "renovation-complete"
    | "sold"
    | "stabilized"
    | "under-construction"
    | null;
  city: string | null;
  state: string | null;
  metraStation: string | null;
  walkMinutes: number | null;
  unitCount: number | null;
  retailUnitCount: number | null;
  yearBuilt: number | null;
  cardBlurb: string | null;
  image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  } | null;
}>;

// Source: src/sanity/queries.ts
// Variable: PROPERTY_BY_SLUG_QUERY
// Query: *[_type == "property" && slug.current == $slug][0] {    _id, title, "slug": slug.current, assetClass, status, city, state,    metraStation, walkMinutes, unitCount, retailUnitCount, yearBuilt, cardBlurb,    "image": gallery[0],    squareFeet, yearRenovated, overview, businessPlan,    gallery, coordinates, dealStory, publiclyOffered,    "relatedPosts": *[_type == "post" && relatedProperty._ref == ^._id] | order(publishedAt desc) {      title, "slug": slug.current, publishedAt    }  }
export type PROPERTY_BY_SLUG_QUERY_RESULT = {
  _id: string;
  title: string | null;
  slug: string | null;
  assetClass:
    "industrial" | "mixed-use" | "multifamily" | "senior" | "townhomes" | null;
  status:
    | "lease-up"
    | "renovation-complete"
    | "sold"
    | "stabilized"
    | "under-construction"
    | null;
  city: string | null;
  state: string | null;
  metraStation: string | null;
  walkMinutes: number | null;
  unitCount: number | null;
  retailUnitCount: number | null;
  yearBuilt: number | null;
  cardBlurb: string | null;
  image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  } | null;
  squareFeet: number | null;
  yearRenovated: number | null;
  overview: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  businessPlan: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  gallery: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  }> | null;
  coordinates: Geopoint | null;
  dealStory: {
    acquired?: string;
    executed?: string;
    exited?: string;
    equityMultiple?: string;
    exitYear?: number;
  } | null;
  publiclyOffered: boolean | null;
  relatedPosts: Array<{
    title: string | null;
    slug: string | null;
    publishedAt: string | null;
  }>;
} | null;

// Source: src/sanity/queries.ts
// Variable: PROPERTY_SLUGS_QUERY
// Query: *[_type == "property" && defined(slug.current)].slug.current
export type PROPERTY_SLUGS_QUERY_RESULT = Array<string | null>;

// Source: src/sanity/queries.ts
// Variable: SOLD_PROPERTIES_QUERY
// Query: *[_type == "property" && status == "sold"] | order(dealStory.exitYear desc) {    _id, title, "slug": slug.current, assetClass, status, city, state,    metraStation, walkMinutes, unitCount, retailUnitCount, yearBuilt, cardBlurb,    "image": gallery[0],    dealStory  }
export type SOLD_PROPERTIES_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  assetClass:
    "industrial" | "mixed-use" | "multifamily" | "senior" | "townhomes" | null;
  status: "sold";
  city: string | null;
  state: string | null;
  metraStation: string | null;
  walkMinutes: number | null;
  unitCount: number | null;
  retailUnitCount: number | null;
  yearBuilt: number | null;
  cardBlurb: string | null;
  image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  } | null;
  dealStory: {
    acquired?: string;
    executed?: string;
    exited?: string;
    equityMultiple?: string;
    exitYear?: number;
  } | null;
}>;

// Source: src/sanity/queries.ts
// Variable: ALL_POSTS_QUERY
// Query: *[_type == "post"] | order(publishedAt desc) {    _id, title, "slug": slug.current, publishedAt, category, excerpt, heroImage  }
export type ALL_POSTS_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  publishedAt: string | null;
  category:
    | "announcement"
    | "design"
    | "market"
    | "municipal-partnership"
    | "operations"
    | null;
  excerpt: string | null;
  heroImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
}>;

// Source: src/sanity/queries.ts
// Variable: POST_BY_SLUG_QUERY
// Query: *[_type == "post" && slug.current == $slug][0] {    title, "slug": slug.current, publishedAt, category, excerpt, heroImage, body,    relatedProperty-> { title, "slug": slug.current, city, unitCount, retailUnitCount, walkMinutes, "image": gallery[0] }  }
export type POST_BY_SLUG_QUERY_RESULT = {
  title: string | null;
  slug: string | null;
  publishedAt: string | null;
  category:
    | "announcement"
    | "design"
    | "market"
    | "municipal-partnership"
    | "operations"
    | null;
  excerpt: string | null;
  heroImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  body: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
        _key: string;
      }
  > | null;
  relatedProperty: {
    title: string | null;
    slug: string | null;
    city: string | null;
    unitCount: number | null;
    retailUnitCount: number | null;
    walkMinutes: number | null;
    image: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
      _key: string;
    } | null;
  } | null;
} | null;

// Source: src/sanity/queries.ts
// Variable: POST_SLUGS_QUERY
// Query: *[_type == "post" && defined(slug.current)].slug.current
export type POST_SLUGS_QUERY_RESULT = Array<string | null>;

// Source: src/sanity/queries.ts
// Variable: TEAM_QUERY
// Query: *[_type == "teamMember"] | order(order asc) { _id, name, role, bio, photo, linkedin }
export type TEAM_QUERY_RESULT = Array<{
  _id: string;
  name: string | null;
  role: string | null;
  bio: string | null;
  photo: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  linkedin: string | null;
}>;

// Source: src/sanity/queries.ts
// Variable: HERO_STATS_QUERY
// Query: *[_type == "heroStat"] | order(order asc) { _id, figure, label }
export type HERO_STATS_QUERY_RESULT = Array<{
  _id: string;
  figure: string | null;
  label: string | null;
}>;

// Source: src/sanity/queries.ts
// Variable: FOCUS_CARDS_QUERY
// Query: *[_type == "focusCard"] | order(order asc) { _id, title, description }
export type FOCUS_CARDS_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  description: string | null;
}>;

// Source: src/sanity/queries.ts
// Variable: TESTIMONIALS_QUERY
// Query: *[_type == "testimonial" && consentOnRecord == true] | order(order asc) {    _id, quote, attribution, descriptor, investorSince, featured  }
export type TESTIMONIALS_QUERY_RESULT = Array<{
  _id: string;
  quote: string | null;
  attribution: string | null;
  descriptor: string | null;
  investorSince: number | null;
  featured: boolean | null;
}>;

// Source: src/sanity/queries.ts
// Variable: SITE_SETTINGS_QUERY
// Query: *[_type == "siteSettings"][0] { agoraPortalUrl, contactEmail, disclaimer, defaultShareImage }
export type SITE_SETTINGS_QUERY_RESULT = {
  agoraPortalUrl: string | null;
  contactEmail: string | null;
  disclaimer: string | null;
  defaultShareImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[_type == "property"] | order(order asc) {\n    _id, title, "slug": slug.current, assetClass, status, city, state,\n    metraStation, walkMinutes, unitCount, retailUnitCount, yearBuilt, cardBlurb,\n    "image": gallery[0]\n  }\n': ALL_PROPERTIES_QUERY_RESULT;
    '\n  *[_type == "property" && slug.current == $slug][0] {\n    _id, title, "slug": slug.current, assetClass, status, city, state,\n    metraStation, walkMinutes, unitCount, retailUnitCount, yearBuilt, cardBlurb,\n    "image": gallery[0],\n    squareFeet, yearRenovated, overview, businessPlan,\n    gallery, coordinates, dealStory, publiclyOffered,\n    "relatedPosts": *[_type == "post" && relatedProperty._ref == ^._id] | order(publishedAt desc) {\n      title, "slug": slug.current, publishedAt\n    }\n  }\n': PROPERTY_BY_SLUG_QUERY_RESULT;
    '*[_type == "property" && defined(slug.current)].slug.current': PROPERTY_SLUGS_QUERY_RESULT;
    '\n  *[_type == "property" && status == "sold"] | order(dealStory.exitYear desc) {\n    _id, title, "slug": slug.current, assetClass, status, city, state,\n    metraStation, walkMinutes, unitCount, retailUnitCount, yearBuilt, cardBlurb,\n    "image": gallery[0],\n    dealStory\n  }\n': SOLD_PROPERTIES_QUERY_RESULT;
    '\n  *[_type == "post"] | order(publishedAt desc) {\n    _id, title, "slug": slug.current, publishedAt, category, excerpt, heroImage\n  }\n': ALL_POSTS_QUERY_RESULT;
    '\n  *[_type == "post" && slug.current == $slug][0] {\n    title, "slug": slug.current, publishedAt, category, excerpt, heroImage, body,\n    relatedProperty-> { title, "slug": slug.current, city, unitCount, retailUnitCount, walkMinutes, "image": gallery[0] }\n  }\n': POST_BY_SLUG_QUERY_RESULT;
    '*[_type == "post" && defined(slug.current)].slug.current': POST_SLUGS_QUERY_RESULT;
    '*[_type == "teamMember"] | order(order asc) { _id, name, role, bio, photo, linkedin }': TEAM_QUERY_RESULT;
    '*[_type == "heroStat"] | order(order asc) { _id, figure, label }': HERO_STATS_QUERY_RESULT;
    '*[_type == "focusCard"] | order(order asc) { _id, title, description }': FOCUS_CARDS_QUERY_RESULT;
    '\n  *[_type == "testimonial" && consentOnRecord == true] | order(order asc) {\n    _id, quote, attribution, descriptor, investorSince, featured\n  }\n': TESTIMONIALS_QUERY_RESULT;
    '*[_type == "siteSettings"][0] { agoraPortalUrl, contactEmail, disclaimer, defaultShareImage }': SITE_SETTINGS_QUERY_RESULT;
  }
}
