/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type PopupBlock = {
  _type: "popupBlock";
  enabled?: boolean;
  eyebrow?: string;
  title?: string;
  body?: string;
  submitLabel?: string;
  successMessage?: string;
};

export type CtaBand = {
  _type: "ctaBand";
  heading?: HeadingBlock;
  submitLabel?: string;
  successMessage?: string;
  callTitle?: string;
  callBody?: string;
  callLabel?: string;
};

export type SeoBlock = {
  _type: "seoBlock";
  title?: string;
  description?: string;
};

export type FactItem = {
  _type: "factItem";
  label?: string;
  value?: string;
};

export type StepItem = {
  _type: "stepItem";
  title?: string;
  body?: string;
};

export type LabelledCard = {
  _type: "labelledCard";
  eyebrow?: string;
  title?: string;
  body?: string;
};

export type HeroBlock = {
  _type: "heroBlock";
  eyebrow?: string;
  title?: string;
  titleAccent?: string;
  titleSuffix?: string;
  intro?: string;
  primaryCta?: CtaLink;
  secondaryCta?: CtaLink;
};

export type HeadingBlock = {
  _type: "headingBlock";
  eyebrow?: string;
  title?: string;
  intro?: string;
};

export type CtaLink = {
  _type: "ctaLink";
  label?: string;
  href?: string;
};

export type TrackRecordPage = {
  _id: string;
  _type: "trackRecordPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  seo?: SeoBlock;
  heading?: HeadingBlock;
};

export type InsightsPage = {
  _id: string;
  _type: "insightsPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  seo?: SeoBlock;
  heading?: HeadingBlock;
};

export type PortfolioPage = {
  _id: string;
  _type: "portfolioPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  seo?: SeoBlock;
  heading?: HeadingBlock;
};

export type InvestorsPage = {
  _id: string;
  _type: "investorsPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  seo?: SeoBlock;
  heading?: HeadingBlock;
  loginLabel?: string;
  stepsTitle?: string;
  steps?: Array<
    {
      _key: string;
    } & StepItem
  >;
  keepInTouchHeading?: HeadingBlock;
  submitLabel?: string;
  testimonialsHeading?: HeadingBlock;
};

export type PartnersPage = {
  _id: string;
  _type: "partnersPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  seo?: SeoBlock;
  heading?: HeadingBlock;
  partners?: Array<
    {
      _key: string;
    } & LabelledCard
  >;
  submissionHeading?: HeadingBlock;
  facts?: Array<
    {
      _key: string;
    } & FactItem
  >;
  formTitle?: string;
  submitLabel?: string;
};

export type AboutPage = {
  _id: string;
  _type: "aboutPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  seo?: SeoBlock;
  hero?: HeroBlock;
  factorsHeading?: HeadingBlock;
  leadershipTitle?: string;
  boardTitle?: string;
};

export type HomePage = {
  _id: string;
  _type: "homePage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  seo?: SeoBlock;
  hero?: HeroBlock;
  factorsHeading?: HeadingBlock;
  insightsHeading?: HeadingBlock;
  portfolioHeading?: HeadingBlock;
  offeringsHeading?: HeadingBlock;
  testimonialsHeading?: HeadingBlock;
  partnersTeaser?: HeadingBlock;
  partnersTeaserCta?: CtaLink;
  portfolioCta?: CtaLink;
  popup?: PopupBlock;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type PropertyReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "property";
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  agoraPortalUrl?: string;
  contactEmail?: string;
  bookACallUrl?: string;
  heroCarousel?: Array<{
    image?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    };
    property?: PropertyReference;
    _type: "carouselSlide";
    _key: string;
  }>;
  defaultShareImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  ctaBand?: CtaBand;
  disclaimer?: string;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Lead = {
  _id: string;
  _type: "lead";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  source?:
    "keep-in-touch" | "site-submission" | "newsletter" | "homepage-popup";
  firstName?: string;
  lastName?: string;
  email?: string;
  phone?: string;
  investorType?: string;
  checkSize?: string;
  accreditedConfirmed?: boolean;
  propertyAddress?: string;
  message?: string;
  submittedAt?: string;
  emailed?: boolean;
  exportedToAgora?: boolean;
};

export type Testimonial = {
  _id: string;
  _type: "testimonial";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  quote?: string;
  attribution?: string;
  descriptor?: string;
  investorSince?: number;
  consentOnRecord?: boolean;
  featured?: boolean;
  order?: number;
};

export type FocusCard = {
  _id: string;
  _type: "focusCard";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  description?: string;
  order?: number;
};

export type HeroStat = {
  _id: string;
  _type: "heroStat";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  figure?: string;
  label?: string;
  order?: number;
};

export type TeamMember = {
  _id: string;
  _type: "teamMember";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  role?: string;
  bio?: string;
  photo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  group?: "leadership" | "partner-board";
  linkedin?: string;
  order?: number;
};

export type Post = {
  _id: string;
  _type: "post";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  publishedAt?: string;
  category?:
    | "municipal-partnership"
    | "design"
    | "operations"
    | "market"
    | "announcement";
  excerpt?: string;
  heroImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  body?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
        _key: string;
      }
  >;
  relatedProperty?: PropertyReference;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type Property = {
  _id: string;
  _type: "property";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  assetClass?:
    | "multifamily"
    | "mixed-use"
    | "townhomes"
    | "industrial"
    | "retail"
    | "senior";
  status?:
    | "under-contract"
    | "stabilized"
    | "lease-up"
    | "under-construction"
    | "renovation-complete"
    | "sold";
  city?: string;
  state?: string;
  coordinates?: Geopoint;
  metraStation?: string;
  walkMinutes?: number;
  unitCount?: number;
  retailUnitCount?: number;
  squareFeet?: number;
  yearBuilt?: number;
  yearRenovated?: number;
  cardBlurb?: string;
  overview?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  businessPlan?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  gallery?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  }>;
  dealStory?: {
    acquired?: string;
    executed?: string;
    exited?: string;
    equityMultiple?: string;
    exitYear?: number;
  };
  publiclyOffered?: boolean;
  offering?: {
    summary?: string;
    targetIrr?: string;
    targetEquityMultiple?: string;
    targetHoldYears?: number;
    dealRoomUrl?: string;
  };
  showInPortfolio?: boolean;
  featured?: boolean;
  order?: number;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type AllSanitySchemaTypes =
  | PopupBlock
  | CtaBand
  | SeoBlock
  | FactItem
  | StepItem
  | LabelledCard
  | HeroBlock
  | HeadingBlock
  | CtaLink
  | TrackRecordPage
  | InsightsPage
  | PortfolioPage
  | InvestorsPage
  | PartnersPage
  | AboutPage
  | HomePage
  | SanityImageAssetReference
  | PropertyReference
  | SiteSettings
  | SanityImageCrop
  | SanityImageHotspot
  | Lead
  | Testimonial
  | FocusCard
  | HeroStat
  | TeamMember
  | Post
  | Slug
  | Property
  | Geopoint
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset;

// Source: src/sanity/queries.ts
// Variable: ALL_PROPERTIES_QUERY
// Query: *[_type == "property" && showInPortfolio != false] | order(order asc) {    _id, title, "slug": slug.current, assetClass, status, city, state,    metraStation, walkMinutes, unitCount, retailUnitCount, yearBuilt, cardBlurb,    "image": gallery[0]  }
export type ALL_PROPERTIES_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  assetClass:
    | "industrial"
    | "mixed-use"
    | "multifamily"
    | "retail"
    | "senior"
    | "townhomes"
    | null;
  status:
    | "lease-up"
    | "renovation-complete"
    | "sold"
    | "stabilized"
    | "under-construction"
    | "under-contract"
    | null;
  city: string | null;
  state: string | null;
  metraStation: string | null;
  walkMinutes: number | null;
  unitCount: number | null;
  retailUnitCount: number | null;
  yearBuilt: number | null;
  cardBlurb: string | null;
  image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  } | null;
}>;

// Source: src/sanity/queries.ts
// Variable: PROPERTY_BY_SLUG_QUERY
// Query: *[_type == "property" && slug.current == $slug][0] {    _id, title, "slug": slug.current, assetClass, status, city, state,    metraStation, walkMinutes, unitCount, retailUnitCount, yearBuilt, cardBlurb,    "image": gallery[0],    squareFeet, yearRenovated, overview, businessPlan,    gallery, coordinates, dealStory, publiclyOffered, offering,    "relatedPosts": *[_type == "post" && relatedProperty._ref == ^._id] | order(publishedAt desc) {      title, "slug": slug.current, publishedAt    }  }
export type PROPERTY_BY_SLUG_QUERY_RESULT = {
  _id: string;
  title: string | null;
  slug: string | null;
  assetClass:
    | "industrial"
    | "mixed-use"
    | "multifamily"
    | "retail"
    | "senior"
    | "townhomes"
    | null;
  status:
    | "lease-up"
    | "renovation-complete"
    | "sold"
    | "stabilized"
    | "under-construction"
    | "under-contract"
    | null;
  city: string | null;
  state: string | null;
  metraStation: string | null;
  walkMinutes: number | null;
  unitCount: number | null;
  retailUnitCount: number | null;
  yearBuilt: number | null;
  cardBlurb: string | null;
  image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  } | null;
  squareFeet: number | null;
  yearRenovated: number | null;
  overview: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  businessPlan: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  gallery: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  }> | null;
  coordinates: Geopoint | null;
  dealStory: {
    acquired?: string;
    executed?: string;
    exited?: string;
    equityMultiple?: string;
    exitYear?: number;
  } | null;
  publiclyOffered: boolean | null;
  offering: {
    summary?: string;
    targetIrr?: string;
    targetEquityMultiple?: string;
    targetHoldYears?: number;
    dealRoomUrl?: string;
  } | null;
  relatedPosts: Array<{
    title: string | null;
    slug: string | null;
    publishedAt: string | null;
  }>;
} | null;

// Source: src/sanity/queries.ts
// Variable: PROPERTY_SLUGS_QUERY
// Query: *[_type == "property" && defined(slug.current)].slug.current
export type PROPERTY_SLUGS_QUERY_RESULT = Array<string | null>;

// Source: src/sanity/queries.ts
// Variable: SOLD_PROPERTIES_QUERY
// Query: *[_type == "property" && status == "sold"] | order(dealStory.exitYear desc) {    _id, title, "slug": slug.current, assetClass, status, city, state,    metraStation, walkMinutes, unitCount, retailUnitCount, yearBuilt, cardBlurb,    "image": gallery[0],    dealStory  }
export type SOLD_PROPERTIES_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  assetClass:
    | "industrial"
    | "mixed-use"
    | "multifamily"
    | "retail"
    | "senior"
    | "townhomes"
    | null;
  status: "sold";
  city: string | null;
  state: string | null;
  metraStation: string | null;
  walkMinutes: number | null;
  unitCount: number | null;
  retailUnitCount: number | null;
  yearBuilt: number | null;
  cardBlurb: string | null;
  image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  } | null;
  dealStory: {
    acquired?: string;
    executed?: string;
    exited?: string;
    equityMultiple?: string;
    exitYear?: number;
  } | null;
}>;

// Source: src/sanity/queries.ts
// Variable: ALL_POSTS_QUERY
// Query: *[_type == "post"] | order(publishedAt desc) {    _id, title, "slug": slug.current, publishedAt, category, excerpt, heroImage  }
export type ALL_POSTS_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  publishedAt: string | null;
  category:
    | "announcement"
    | "design"
    | "market"
    | "municipal-partnership"
    | "operations"
    | null;
  excerpt: string | null;
  heroImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
}>;

// Source: src/sanity/queries.ts
// Variable: POST_BY_SLUG_QUERY
// Query: *[_type == "post" && slug.current == $slug][0] {    title, "slug": slug.current, publishedAt, category, excerpt, heroImage, body,    relatedProperty-> { title, "slug": slug.current, city, unitCount, retailUnitCount, walkMinutes, "image": gallery[0] }  }
export type POST_BY_SLUG_QUERY_RESULT = {
  title: string | null;
  slug: string | null;
  publishedAt: string | null;
  category:
    | "announcement"
    | "design"
    | "market"
    | "municipal-partnership"
    | "operations"
    | null;
  excerpt: string | null;
  heroImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  body: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
        _key: string;
      }
  > | null;
  relatedProperty: {
    title: string | null;
    slug: string | null;
    city: string | null;
    unitCount: number | null;
    retailUnitCount: number | null;
    walkMinutes: number | null;
    image: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
      _key: string;
    } | null;
  } | null;
} | null;

// Source: src/sanity/queries.ts
// Variable: POST_SLUGS_QUERY
// Query: *[_type == "post" && defined(slug.current)].slug.current
export type POST_SLUGS_QUERY_RESULT = Array<string | null>;

// Source: src/sanity/queries.ts
// Variable: TEAM_QUERY
// Query: *[_type == "teamMember"] | order(order asc) { _id, name, role, bio, photo, linkedin, group }
export type TEAM_QUERY_RESULT = Array<{
  _id: string;
  name: string | null;
  role: string | null;
  bio: string | null;
  photo: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  linkedin: string | null;
  group: "leadership" | "partner-board" | null;
}>;

// Source: src/sanity/queries.ts
// Variable: HERO_STATS_QUERY
// Query: *[_type == "heroStat"] | order(order asc) { _id, figure, label }
export type HERO_STATS_QUERY_RESULT = Array<{
  _id: string;
  figure: string | null;
  label: string | null;
}>;

// Source: src/sanity/queries.ts
// Variable: FOCUS_CARDS_QUERY
// Query: *[_type == "focusCard"] | order(order asc) { _id, title, description }
export type FOCUS_CARDS_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  description: string | null;
}>;

// Source: src/sanity/queries.ts
// Variable: TESTIMONIALS_QUERY
// Query: *[_type == "testimonial" && consentOnRecord == true] | order(order asc) {    _id, quote, attribution, descriptor, investorSince, featured  }
export type TESTIMONIALS_QUERY_RESULT = Array<{
  _id: string;
  quote: string | null;
  attribution: string | null;
  descriptor: string | null;
  investorSince: number | null;
  featured: boolean | null;
}>;

// Source: src/sanity/queries.ts
// Variable: CURRENT_OFFERINGS_QUERY
// Query: *[_type == "property" && publiclyOffered == true] | order(order asc) {    _id, title, "slug": slug.current, assetClass, status, city, state,    metraStation, walkMinutes, unitCount, retailUnitCount, yearBuilt, cardBlurb,    "image": gallery[0], offering  }
export type CURRENT_OFFERINGS_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  assetClass:
    | "industrial"
    | "mixed-use"
    | "multifamily"
    | "retail"
    | "senior"
    | "townhomes"
    | null;
  status:
    | "lease-up"
    | "renovation-complete"
    | "sold"
    | "stabilized"
    | "under-construction"
    | "under-contract"
    | null;
  city: string | null;
  state: string | null;
  metraStation: string | null;
  walkMinutes: number | null;
  unitCount: number | null;
  retailUnitCount: number | null;
  yearBuilt: number | null;
  cardBlurb: string | null;
  image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  } | null;
  offering: {
    summary?: string;
    targetIrr?: string;
    targetEquityMultiple?: string;
    targetHoldYears?: number;
    dealRoomUrl?: string;
  } | null;
}>;

// Source: src/sanity/queries.ts
// Variable: SITE_SETTINGS_QUERY
// Query: *[_type == "siteSettings"][0] {    agoraPortalUrl, contactEmail, bookACallUrl, disclaimer, defaultShareImage,    ctaBand {      heading { eyebrow, title, intro },      submitLabel, successMessage, callTitle, callBody, callLabel    },    heroCarousel[]{ image, "slug": property->slug.current, "propertyTitle": property->title }  }
export type SITE_SETTINGS_QUERY_RESULT = {
  agoraPortalUrl: string | null;
  contactEmail: string | null;
  bookACallUrl: string | null;
  disclaimer: string | null;
  defaultShareImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  ctaBand: {
    heading: {
      eyebrow: string | null;
      title: string | null;
      intro: string | null;
    } | null;
    submitLabel: string | null;
    successMessage: string | null;
    callTitle: string | null;
    callBody: string | null;
    callLabel: string | null;
  } | null;
  heroCarousel: Array<{
    image: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    } | null;
    slug: string | null;
    propertyTitle: string | null;
  }> | null;
} | null;

// Source: src/sanity/queries.ts
// Variable: HOME_PAGE_QUERY
// Query: *[_id == "homePage"][0] {    seo { title, description },    hero { eyebrow, title, titleAccent, titleSuffix, intro,           primaryCta { label, href }, secondaryCta { label, href } },    factorsHeading { eyebrow, title, intro },    insightsHeading { eyebrow, title, intro },    portfolioHeading { eyebrow, title, intro },    offeringsHeading { eyebrow, title, intro },    testimonialsHeading { eyebrow, title, intro },    partnersTeaser { eyebrow, title, intro },    partnersTeaserCta { label, href },    portfolioCta { label, href },    popup { enabled, eyebrow, title, body, submitLabel, successMessage }  }
export type HOME_PAGE_QUERY_RESULT =
  | {
      seo: null;
      hero: null;
      factorsHeading: null;
      insightsHeading: null;
      portfolioHeading: null;
      offeringsHeading: null;
      testimonialsHeading: null;
      partnersTeaser: null;
      partnersTeaserCta: null;
      portfolioCta: null;
      popup: null;
    }
  | {
      seo: {
        title: string | null;
        description: string | null;
      } | null;
      hero: null;
      factorsHeading: null;
      insightsHeading: null;
      portfolioHeading: null;
      offeringsHeading: null;
      testimonialsHeading: null;
      partnersTeaser: null;
      partnersTeaserCta: null;
      portfolioCta: null;
      popup: null;
    }
  | {
      seo: {
        title: string | null;
        description: string | null;
      } | null;
      hero: null;
      factorsHeading: null;
      insightsHeading: null;
      portfolioHeading: null;
      offeringsHeading: null;
      testimonialsHeading: {
        eyebrow: string | null;
        title: string | null;
        intro: string | null;
      } | null;
      partnersTeaser: null;
      partnersTeaserCta: null;
      portfolioCta: null;
      popup: null;
    }
  | {
      seo: {
        title: string | null;
        description: string | null;
      } | null;
      hero: {
        eyebrow: string | null;
        title: string | null;
        titleAccent: string | null;
        titleSuffix: string | null;
        intro: string | null;
        primaryCta: {
          label: string | null;
          href: string | null;
        } | null;
        secondaryCta: {
          label: string | null;
          href: string | null;
        } | null;
      } | null;
      factorsHeading: {
        eyebrow: string | null;
        title: string | null;
        intro: string | null;
      } | null;
      insightsHeading: null;
      portfolioHeading: null;
      offeringsHeading: null;
      testimonialsHeading: null;
      partnersTeaser: null;
      partnersTeaserCta: null;
      portfolioCta: null;
      popup: null;
    }
  | {
      seo: {
        title: string | null;
        description: string | null;
      } | null;
      hero: {
        eyebrow: string | null;
        title: string | null;
        titleAccent: string | null;
        titleSuffix: string | null;
        intro: string | null;
        primaryCta: {
          label: string | null;
          href: string | null;
        } | null;
        secondaryCta: {
          label: string | null;
          href: string | null;
        } | null;
      } | null;
      factorsHeading: {
        eyebrow: string | null;
        title: string | null;
        intro: string | null;
      } | null;
      insightsHeading: {
        eyebrow: string | null;
        title: string | null;
        intro: string | null;
      } | null;
      portfolioHeading: {
        eyebrow: string | null;
        title: string | null;
        intro: string | null;
      } | null;
      offeringsHeading: {
        eyebrow: string | null;
        title: string | null;
        intro: string | null;
      } | null;
      testimonialsHeading: {
        eyebrow: string | null;
        title: string | null;
        intro: string | null;
      } | null;
      partnersTeaser: {
        eyebrow: string | null;
        title: string | null;
        intro: string | null;
      } | null;
      partnersTeaserCta: {
        label: string | null;
        href: string | null;
      } | null;
      portfolioCta: {
        label: string | null;
        href: string | null;
      } | null;
      popup: {
        enabled: boolean | null;
        eyebrow: string | null;
        title: string | null;
        body: string | null;
        submitLabel: string | null;
        successMessage: string | null;
      } | null;
    }
  | null;

// Source: src/sanity/queries.ts
// Variable: ABOUT_PAGE_QUERY
// Query: *[_id == "aboutPage"][0] {    seo { title, description },    hero { eyebrow, title, titleAccent, titleSuffix, intro },    factorsHeading { eyebrow, title, intro },    leadershipTitle,    boardTitle  }
export type ABOUT_PAGE_QUERY_RESULT =
  | {
      seo: null;
      hero: null;
      factorsHeading: null;
      leadershipTitle: null;
      boardTitle: null;
    }
  | {
      seo: {
        title: string | null;
        description: string | null;
      } | null;
      hero: null;
      factorsHeading: null;
      leadershipTitle: null;
      boardTitle: null;
    }
  | {
      seo: {
        title: string | null;
        description: string | null;
      } | null;
      hero: {
        eyebrow: string | null;
        title: string | null;
        titleAccent: string | null;
        titleSuffix: string | null;
        intro: string | null;
      } | null;
      factorsHeading: {
        eyebrow: string | null;
        title: string | null;
        intro: string | null;
      } | null;
      leadershipTitle: null;
      boardTitle: null;
    }
  | {
      seo: {
        title: string | null;
        description: string | null;
      } | null;
      hero: {
        eyebrow: string | null;
        title: string | null;
        titleAccent: string | null;
        titleSuffix: string | null;
        intro: string | null;
      } | null;
      factorsHeading: {
        eyebrow: string | null;
        title: string | null;
        intro: string | null;
      } | null;
      leadershipTitle: string | null;
      boardTitle: string | null;
    }
  | null;

// Source: src/sanity/queries.ts
// Variable: PARTNERS_PAGE_QUERY
// Query: *[_id == "partnersPage"][0] {    seo { title, description },    heading { eyebrow, title, intro },    partners[] { eyebrow, title, body },    submissionHeading { eyebrow, title, intro },    facts[] { label, value },    formTitle,    submitLabel  }
export type PARTNERS_PAGE_QUERY_RESULT =
  | {
      seo: null;
      heading: null;
      partners: null;
      submissionHeading: null;
      facts: null;
      formTitle: null;
      submitLabel: null;
    }
  | {
      seo: {
        title: string | null;
        description: string | null;
      } | null;
      heading: null;
      partners: null;
      submissionHeading: null;
      facts: null;
      formTitle: null;
      submitLabel: null;
    }
  | {
      seo: {
        title: string | null;
        description: string | null;
      } | null;
      heading: {
        eyebrow: string | null;
        title: string | null;
        intro: string | null;
      } | null;
      partners: null;
      submissionHeading: null;
      facts: null;
      formTitle: null;
      submitLabel: null;
    }
  | {
      seo: {
        title: string | null;
        description: string | null;
      } | null;
      heading: {
        eyebrow: string | null;
        title: string | null;
        intro: string | null;
      } | null;
      partners: null;
      submissionHeading: null;
      facts: null;
      formTitle: null;
      submitLabel: string | null;
    }
  | {
      seo: {
        title: string | null;
        description: string | null;
      } | null;
      heading: {
        eyebrow: string | null;
        title: string | null;
        intro: string | null;
      } | null;
      partners: Array<{
        eyebrow: string | null;
        title: string | null;
        body: string | null;
      }> | null;
      submissionHeading: {
        eyebrow: string | null;
        title: string | null;
        intro: string | null;
      } | null;
      facts: Array<{
        label: string | null;
        value: string | null;
      }> | null;
      formTitle: string | null;
      submitLabel: string | null;
    }
  | null;

// Source: src/sanity/queries.ts
// Variable: INVESTORS_PAGE_QUERY
// Query: *[_id == "investorsPage"][0] {    seo { title, description },    heading { eyebrow, title, intro },    loginLabel,    stepsTitle,    steps[] { title, body },    keepInTouchHeading { eyebrow, title, intro },    submitLabel,    testimonialsHeading { eyebrow, title, intro }  }
export type INVESTORS_PAGE_QUERY_RESULT =
  | {
      seo: null;
      heading: null;
      loginLabel: null;
      stepsTitle: null;
      steps: null;
      keepInTouchHeading: null;
      submitLabel: null;
      testimonialsHeading: null;
    }
  | {
      seo: {
        title: string | null;
        description: string | null;
      } | null;
      heading: null;
      loginLabel: null;
      stepsTitle: null;
      steps: null;
      keepInTouchHeading: null;
      submitLabel: null;
      testimonialsHeading: null;
    }
  | {
      seo: {
        title: string | null;
        description: string | null;
      } | null;
      heading: null;
      loginLabel: null;
      stepsTitle: null;
      steps: null;
      keepInTouchHeading: null;
      submitLabel: null;
      testimonialsHeading: {
        eyebrow: string | null;
        title: string | null;
        intro: string | null;
      } | null;
    }
  | {
      seo: {
        title: string | null;
        description: string | null;
      } | null;
      heading: {
        eyebrow: string | null;
        title: string | null;
        intro: string | null;
      } | null;
      loginLabel: null;
      stepsTitle: null;
      steps: null;
      keepInTouchHeading: null;
      submitLabel: null;
      testimonialsHeading: null;
    }
  | {
      seo: {
        title: string | null;
        description: string | null;
      } | null;
      heading: {
        eyebrow: string | null;
        title: string | null;
        intro: string | null;
      } | null;
      loginLabel: null;
      stepsTitle: null;
      steps: null;
      keepInTouchHeading: null;
      submitLabel: string | null;
      testimonialsHeading: null;
    }
  | {
      seo: {
        title: string | null;
        description: string | null;
      } | null;
      heading: {
        eyebrow: string | null;
        title: string | null;
        intro: string | null;
      } | null;
      loginLabel: string | null;
      stepsTitle: string | null;
      steps: Array<{
        title: string | null;
        body: string | null;
      }> | null;
      keepInTouchHeading: {
        eyebrow: string | null;
        title: string | null;
        intro: string | null;
      } | null;
      submitLabel: string | null;
      testimonialsHeading: {
        eyebrow: string | null;
        title: string | null;
        intro: string | null;
      } | null;
    }
  | null;

// Source: src/sanity/queries.ts
// Variable: PORTFOLIO_PAGE_QUERY
// Query: *[_id == "portfolioPage"][0] {    seo { title, description },    heading { eyebrow, title, intro }  }
export type PORTFOLIO_PAGE_QUERY_RESULT =
  | {
      seo: null;
      heading: null;
    }
  | {
      seo: {
        title: string | null;
        description: string | null;
      } | null;
      heading: null;
    }
  | {
      seo: {
        title: string | null;
        description: string | null;
      } | null;
      heading: {
        eyebrow: string | null;
        title: string | null;
        intro: string | null;
      } | null;
    }
  | null;

// Source: src/sanity/queries.ts
// Variable: INSIGHTS_PAGE_QUERY
// Query: *[_id == "insightsPage"][0] {    seo { title, description },    heading { eyebrow, title, intro }  }
export type INSIGHTS_PAGE_QUERY_RESULT =
  | {
      seo: null;
      heading: null;
    }
  | {
      seo: {
        title: string | null;
        description: string | null;
      } | null;
      heading: null;
    }
  | {
      seo: {
        title: string | null;
        description: string | null;
      } | null;
      heading: {
        eyebrow: string | null;
        title: string | null;
        intro: string | null;
      } | null;
    }
  | null;

// Source: src/sanity/queries.ts
// Variable: TRACK_RECORD_PAGE_QUERY
// Query: *[_id == "trackRecordPage"][0] {    seo { title, description },    heading { eyebrow, title, intro }  }
export type TRACK_RECORD_PAGE_QUERY_RESULT =
  | {
      seo: null;
      heading: null;
    }
  | {
      seo: {
        title: string | null;
        description: string | null;
      } | null;
      heading: null;
    }
  | {
      seo: {
        title: string | null;
        description: string | null;
      } | null;
      heading: {
        eyebrow: string | null;
        title: string | null;
        intro: string | null;
      } | null;
    }
  | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[_type == "property" && showInPortfolio != false] | order(order asc) {\n    _id, title, "slug": slug.current, assetClass, status, city, state,\n    metraStation, walkMinutes, unitCount, retailUnitCount, yearBuilt, cardBlurb,\n    "image": gallery[0]\n  }\n': ALL_PROPERTIES_QUERY_RESULT;
    '\n  *[_type == "property" && slug.current == $slug][0] {\n    _id, title, "slug": slug.current, assetClass, status, city, state,\n    metraStation, walkMinutes, unitCount, retailUnitCount, yearBuilt, cardBlurb,\n    "image": gallery[0],\n    squareFeet, yearRenovated, overview, businessPlan,\n    gallery, coordinates, dealStory, publiclyOffered, offering,\n    "relatedPosts": *[_type == "post" && relatedProperty._ref == ^._id] | order(publishedAt desc) {\n      title, "slug": slug.current, publishedAt\n    }\n  }\n': PROPERTY_BY_SLUG_QUERY_RESULT;
    '*[_type == "property" && defined(slug.current)].slug.current': PROPERTY_SLUGS_QUERY_RESULT;
    '\n  *[_type == "property" && status == "sold"] | order(dealStory.exitYear desc) {\n    _id, title, "slug": slug.current, assetClass, status, city, state,\n    metraStation, walkMinutes, unitCount, retailUnitCount, yearBuilt, cardBlurb,\n    "image": gallery[0],\n    dealStory\n  }\n': SOLD_PROPERTIES_QUERY_RESULT;
    '\n  *[_type == "post"] | order(publishedAt desc) {\n    _id, title, "slug": slug.current, publishedAt, category, excerpt, heroImage\n  }\n': ALL_POSTS_QUERY_RESULT;
    '\n  *[_type == "post" && slug.current == $slug][0] {\n    title, "slug": slug.current, publishedAt, category, excerpt, heroImage, body,\n    relatedProperty-> { title, "slug": slug.current, city, unitCount, retailUnitCount, walkMinutes, "image": gallery[0] }\n  }\n': POST_BY_SLUG_QUERY_RESULT;
    '*[_type == "post" && defined(slug.current)].slug.current': POST_SLUGS_QUERY_RESULT;
    '*[_type == "teamMember"] | order(order asc) { _id, name, role, bio, photo, linkedin, group }': TEAM_QUERY_RESULT;
    '*[_type == "heroStat"] | order(order asc) { _id, figure, label }': HERO_STATS_QUERY_RESULT;
    '*[_type == "focusCard"] | order(order asc) { _id, title, description }': FOCUS_CARDS_QUERY_RESULT;
    '\n  *[_type == "testimonial" && consentOnRecord == true] | order(order asc) {\n    _id, quote, attribution, descriptor, investorSince, featured\n  }\n': TESTIMONIALS_QUERY_RESULT;
    '\n  *[_type == "property" && publiclyOffered == true] | order(order asc) {\n    _id, title, "slug": slug.current, assetClass, status, city, state,\n    metraStation, walkMinutes, unitCount, retailUnitCount, yearBuilt, cardBlurb,\n    "image": gallery[0], offering\n  }\n': CURRENT_OFFERINGS_QUERY_RESULT;
    '*[_type == "siteSettings"][0] {\n    agoraPortalUrl, contactEmail, bookACallUrl, disclaimer, defaultShareImage,\n    ctaBand {\n      heading { eyebrow, title, intro },\n      submitLabel, successMessage, callTitle, callBody, callLabel\n    },\n    heroCarousel[]{ image, "slug": property->slug.current, "propertyTitle": property->title }\n  }': SITE_SETTINGS_QUERY_RESULT;
    '\n  *[_id == "homePage"][0] {\n    seo { title, description },\n    hero { eyebrow, title, titleAccent, titleSuffix, intro,\n           primaryCta { label, href }, secondaryCta { label, href } },\n    factorsHeading { eyebrow, title, intro },\n    insightsHeading { eyebrow, title, intro },\n    portfolioHeading { eyebrow, title, intro },\n    offeringsHeading { eyebrow, title, intro },\n    testimonialsHeading { eyebrow, title, intro },\n    partnersTeaser { eyebrow, title, intro },\n    partnersTeaserCta { label, href },\n    portfolioCta { label, href },\n    popup { enabled, eyebrow, title, body, submitLabel, successMessage }\n  }\n': HOME_PAGE_QUERY_RESULT;
    '\n  *[_id == "aboutPage"][0] {\n    seo { title, description },\n    hero { eyebrow, title, titleAccent, titleSuffix, intro },\n    factorsHeading { eyebrow, title, intro },\n    leadershipTitle,\n    boardTitle\n  }\n': ABOUT_PAGE_QUERY_RESULT;
    '\n  *[_id == "partnersPage"][0] {\n    seo { title, description },\n    heading { eyebrow, title, intro },\n    partners[] { eyebrow, title, body },\n    submissionHeading { eyebrow, title, intro },\n    facts[] { label, value },\n    formTitle,\n    submitLabel\n  }\n': PARTNERS_PAGE_QUERY_RESULT;
    '\n  *[_id == "investorsPage"][0] {\n    seo { title, description },\n    heading { eyebrow, title, intro },\n    loginLabel,\n    stepsTitle,\n    steps[] { title, body },\n    keepInTouchHeading { eyebrow, title, intro },\n    submitLabel,\n    testimonialsHeading { eyebrow, title, intro }\n  }\n': INVESTORS_PAGE_QUERY_RESULT;
    '\n  *[_id == "portfolioPage"][0] {\n    seo { title, description },\n    heading { eyebrow, title, intro }\n  }\n': PORTFOLIO_PAGE_QUERY_RESULT;
    '\n  *[_id == "insightsPage"][0] {\n    seo { title, description },\n    heading { eyebrow, title, intro }\n  }\n': INSIGHTS_PAGE_QUERY_RESULT;
    '\n  *[_id == "trackRecordPage"][0] {\n    seo { title, description },\n    heading { eyebrow, title, intro }\n  }\n': TRACK_RECORD_PAGE_QUERY_RESULT;
  }
}
